### ISSUE TITLE
Not working on URP

### ISSUE THREAD

**Issue by nistream** [Ikaroon/TMP3D#33]
**Describe the bug**
The sample scene renders nothing.

**To Reproduce**
1. Add the git package as stated in the README
2. Import the sample files from PackageManager as stated in the README
3. Open the sample scene as stated in the README
4. There's nothing visible in the scene.

**Expected behavior**
A 3D object in the scene.

**Screenshots**
![微信截图_20240718130317](https://github.com/user-attachments/assets/530981cc-b4d8-46d8-8c6d-50e348282c2c)

**Desktop**
 - OS: Windows 11

**Additional context**
 - Unity Editor version: 2021.3.23f1c1
 - Render Pipeline: URP 12.1.11
 - Graphics API: Direct3D11
 - Graphic card: RTX 3070

**Comment by SeanNi1221** [comment]
The problem is gone after upgrading to Unity 2022.3.15f1c1 with Universal RP 14.0.9

**Comment by VariConst** [comment]
For everyone who comes here in order to solve that issue: try to place the line `#pragma multi_compile _VOLUMEMODE_SURFACE _VOLUMEMODE_FULL` directly inside the `TMP3D_Unlit.shader` - somewhere near the similar pragmas in **both** Passes.

Originally that line is inside `Lib/Raymarching/Common.cginc` and somehow it works in Unity 2020.3 (and probably some others), but as I understand it that is completely wrong (and in 2020.3 there is a warning "Ignoring duplicate keyword line 'shader_feature _VOLUMEMODE_SURFACE _VOLUMEMODE_FULL'" from the shader compiler that is related to that) and you should not bury such pragmas in the `#include`-s as they may be completely missed by the compiler and that is what happens in the versions that I tested on - 2019.4, 6.0 and 6.3. There is no any warnings, but the keywords `_VOLUMEMODE_SURFACE` and `_VOLUMEMODE_FULL` are missing from the shader (you can check that in the Keywords region in the shader Inspector window or inside the compiled shader code)
